window.TYPING_WORKBENCH_SCENARIOS = [
  {
    scenarioId: "attendance-overnight-break-not-deducted",
    projectId: "attendance",
    difficulty: "intermediate",
    subject: "勤怠実績登録で日をまたぐ休憩時間が勤務時間から控除されない",
    subjectAnswer: "kinntaijissekitourokudehiwomatagukyuukeijikanngakinnmujikannkarakoujosarenai",
    detail: "22:00から翌日07:00までの勤務に翌日01:00から02:00の休憩を登録すると、実労働時間が8時間ではなく9時間として集計されてしまう",
    detailAnswer: "22:00karayokujitsu07:00madenokinnmuniyokujitsu01:00kara02:00nokyuukeiwotourokusuruto jitsuroudoujikanga8jikandewanaku9jikanntoshiteshuukeisareteshimau",
    expected: "翌日分を含む1時間の休憩を控除し、実労働時間を8時間とすること",
    expectedAnswer: "yokujitsubunwohukumu1jikannokyuukeiwokoujoshi jitsuroudoujikannwo8jikanntosurukoto",
    actual: "1時間の休憩が控除されず、実労働時間が9時間として集計される",
    actualAnswer: "1jikannnokyuukeigakoujosarezu jitsuroudoujikannga9jikanntoshiteshuukeisareru",
    reproducibility: "2/5",
  },
  {
    scenarioId: "attendance-simultaneous-clock-out-double-overtime",
    projectId: "attendance",
    difficulty: "advanced",
    subject: "月末処理中の同時打刻で残業時間が二重計上されてしまう",
    subjectAnswer: "getumatushorichuunodoujidakokudezanngyoujikannganijuukeijousareteshimau",
    detail: "月末処理中に2台の端末から同じ従業員の退勤打刻を同時に送信すると、30分の残業が60分として集計されてしまう",
    detailAnswer: "getumatushorichuuni2dainotanmatukaraonajijuugyouinnnotaikindakokuwodoujinisoushinnsuruto 30punnnozanngyouga60punntoshiteshuukeisareteshimau",
    expected: "同じ退勤打刻を一度だけ処理し、残業時間を30分として集計すること",
    expectedAnswer: "onajitaikindakokuwoichidodakeshorishi zangyoujikanwo30punntoshiteshuukeisurukoto",
    actual: "同じ退勤打刻が2回処理され、残業時間が60分として集計される",
    actualAnswer: "onajitaikindakokuga2kaishorisare zanngyoujikannga60punntoshiteshuukeisareru",
    reproducibility: "1/20",
  },
  {
    scenarioId: "salon-cancelled-slot-remains-booked",
    projectId: "salon",
    difficulty: "intermediate",
    subject: "予約をキャンセルした後も対象時間帯が予約済みのままになってしまう",
    subjectAnswer: "yoyakuwokyannserushitaatomotaishoujikanntaigayoyakuzuminomamaninatteshimau",
    detail: "14:00の予約をキャンセルしても対象時間帯が予約済みのまま表示され、新しい予約を登録できなくなってしまう",
    detailAnswer: "14:00noyoyakuwokyannserushitemotaishoujikanntaigayoyakuzuminomamahyoujisare atarashiiyoyakuwotourokudekinakunatteshimau",
    expected: "キャンセルした時間帯を再度予約できること",
    expectedAnswer: "kyannserushitajikanntaiwosaidoyoyakudekirukoto",
    actual: "キャンセルした14:00枠が予約済みのままで、新しい予約を登録できない",
    actualAnswer: "kyannserushita14:00wakugayoyakuzuminomamade atarashiiyoyakuwotourokudekinai",
    reproducibility: "3/3",
  },
  {
    scenarioId: "salon-simultaneous-double-booking",
    projectId: "salon",
    difficulty: "advanced",
    subject: "複数端末からの同時予約で同じ担当者の予約が二重登録されてしまう",
    subjectAnswer: "fukusuutanmatukaranodoujiyoyakudeonajitanntoushanoyoyakuganijuutourokusareteshimau",
    detail: "2台の端末から300ms以内に同じ担当者の14:00枠を確定すると、それぞれ異なる予約番号で2件登録されてしまう",
    detailAnswer: "2dainotanmatukara300msinainionajitanntoushano14:00wakuwokakuteisuruto sorezorekotonaruyoyakubangoude2kenntourokusareteshimau",
    expected: "先に確定した予約だけが登録されること",
    expectedAnswer: "sakinikakuteishitayoyakudakegatourokusarerukoto",
    actual: "同じ担当者の14:00枠が異なる予約番号で2件登録される",
    actualAnswer: "onajitanntoushano14:00wakugakotonaruyoyakubangoude2kenntourokusareru",
    reproducibility: "1/10",
  },
  {
    scenarioId: "ec-tax-rounding-inconsistent",
    projectId: "ec",
    difficulty: "intermediate",
    subject: "商品一覧画面で税込価格の端数処理が商品ごとに異なってしまう",
    subjectAnswer: "shouhinnitiranngamenndezeikomikakakunohasuushorigashouhinngotonikotonatteshimau",
    detail: "税抜105円・税率10%の同一条件でも、商品Aは115円、商品Bは116円と異なる税込価格が表示されてしまう",
    detailAnswer: "zeinuki105enn zeiritu10%nodouitsujoukenndemo shouhinn a ha115enn shouhinn b ha116enntokotonaruzeikomikakakugahyoujisareteshimau",
    expected: "設定された切り捨て処理を適用し、どちらも税込115円と表示すること",
    expectedAnswer: "setteisarerukirisuteshoriwotekiyoushi dotiramazeikomi115enntohyoujisurukoto",
    actual: "同じ税条件でも商品Aは115円、商品Bは116円と表示される",
    actualAnswer: "onajizeijoukenndemoshouhinn a ha115enn shouhinn b ha116enntohyoujisareru",
    reproducibility: "3/3",
  },
  {
    scenarioId: "ec-payment-notification-double-order",
    projectId: "ec",
    difficulty: "advanced",
    subject: "注文連携で決済通知を再送すると注文が二重確定されてしまう",
    subjectAnswer: "chuumonnrenkeidekessaitsuuchiwosaisousurutichuumonnganijuukakuteisareteshimau",
    detail: "決済通知ID「PAY-4821」を再送すると、1件の決済に対して異なる注文番号が2件発行されてしまう",
    detailAnswer: "kessaitsuuchiid pay-4821wosaisousuruto 1kennokessainitaishitekotonaruchuumonnbangouga2kennhakkousareteshimau",
    expected: "同じ通知を受信しても注文を一度だけ確定すること",
    expectedAnswer: "onajitsuuchiwojushinnshitemochuumonnwoichidodakekakuteisurukoto",
    actual: "1件の決済に対して異なる注文番号が2件発行される",
    actualAnswer: "1kennokessainitaishitekotonaruchuumonnbangouga2kennhakkousareru",
    reproducibility: "1/15",
  },
  {
    scenarioId: "inventory-expired-lot-fifo",
    projectId: "inventory",
    difficulty: "intermediate",
    subject: "出庫登録画面で期限切れのロットが出庫候補に表示されてしまう",
    subjectAnswer: "shukkotourokugamenndekigengirenorottogashukkokouhonihyoujisareteshimau",
    detail: "出庫候補を表示すると、有効期限が2026年7月26日のロットが期限内の8月31日ロットより先に表示されてしまう",
    detailAnswer: "shukkokouhowohyoujisuruto yuukoukigenga2026nenn7gatu26nichinorottogakigennnaino8gatu31nichirottoyorisakinihyoujisareteshimau",
    expected: "有効期限内のロットだけが出庫候補になること",
    expectedAnswer: "yuukoukigennnainorottodakegashukkokouhoninarukoto",
    actual: "期限切れの7月26日ロットが出庫候補の先頭に表示される",
    actualAnswer: "kigengireno7gatu26nichirottogashukkokouhonosenntounihyoujisareru",
    reproducibility: "3/3",
  },
  {
    scenarioId: "inventory-simultaneous-shipment-negative-stock",
    projectId: "inventory",
    difficulty: "advanced",
    subject: "複数端末からの同時出庫で在庫数がマイナスになってしまう",
    subjectAnswer: "fukusuutanmatukaranodoujishukkodezaikosugamainasuninatteshimau",
    detail: "在庫1個の商品を2台の端末から同時に1個ずつ出庫すると、2件とも登録に成功し、在庫数がマイナス1になってしまう",
    detailAnswer: "zaiko1konoshouhinnwo2dainotanmatukaradoujini1kozutushukkosuruto 2kenntomotourokuniseikoushi zaikosugamainasu1ninatteshimau",
    expected: "先に確定した出庫だけを登録し、2件目は在庫不足として処理すること",
    expectedAnswer: "sakinikakuteishitashukkodakewotourokushi 2kenmewazaikobusokutoshiteshorisurukoto",
    actual: "2件の出庫がともに成功し、在庫数がマイナス1になる",
    actualAnswer: "2kenn-noshukkogatomoniseikoushi zaikosugamainasu1ninaru",
    reproducibility: "2/30",
  },
  {
    scenarioId: "mobile-notification-opens-wrong-news",
    projectId: "mobile",
    difficulty: "intermediate",
    subject: "プッシュ通知から開くと別のお知らせが表示されてしまう",
    subjectAnswer: "pusshutsuuchikarahirakutobetunooshirasegahyoujisareteshimau",
    detail: "お知らせID「NEWS-102」のプッシュ通知をタップすると、対象ではなく一つ前の「NEWS-101」が表示されてしまう",
    detailAnswer: "oshiraseid news-102nopusshutsuuchiwotappusuruto taishoudewanakuhitotumaenonews-101gahyoujisareteshimau",
    expected: "タップした通知に対応するお知らせを表示すること",
    expectedAnswer: "tappushitatsuuchinitaiousuruoshirasewohyoujisurukoto",
    actual: "通知対象のNEWS-102ではなく、一つ前のNEWS-101が表示される",
    actualAnswer: "tsuuchitaishounonews-102dewanaku hitotumaenonews-101gahyoujisareru",
    reproducibility: "2/5",
  },
  {
    scenarioId: "mobile-background-sync-data-lost",
    projectId: "mobile",
    difficulty: "advanced",
    subject: "バックグラウンド復帰後に未送信データが消えてしまう",
    subjectAnswer: "bakkuguraundofukkigonimisoushinnde-tagakieteshimau",
    detail: "未送信データ3件が残っている状態でOSによるメモリ解放が発生すると、アプリ復帰後に3件すべてが一覧から消えてしまう",
    detailAnswer: "misoushinnde-ta3kennganokotteirujoutaideosniyorumemorikaihougahasseisuruto apurifukkigoni3kensubetegaitirannkarakieteshimau",
    expected: "未送信データを保持して復帰後に同期すること",
    expectedAnswer: "misoushinnde-tawohojishitefukkigonidoukisurukoto",
    actual: "アプリ復帰後、未送信データ3件がすべて一覧から消失する",
    actualAnswer: "apurifukkigomisoushinnde-ta3kenngasubeteitirannkarashoushitsusuru",
    reproducibility: "1/25",
  },
  {
    scenarioId: "automotive-can-byte-order-reversed",
    projectId: "automotive",
    difficulty: "intermediate",
    subject: "車載メーターでCAN信号がDBC定義と異なる値で表示されてしまう",
    subjectAnswer: "shasaime-ta-decan shinngougadbc teigitokotonaruchidehyoujisareteshimau",
    detail: "DBCでリトルエンディアンと定義された信号に0x0BB8を送信すると、期待値30.00Vに対してメーターに471.15Vと表示されてしまう",
    detailAnswer: "dbcderitoruendiantoteigisaretashingouni0x0bb8wosoushinnsuruto kitaichi30.00vnitaishiteme-ta-ni471.15vtohyoujisareteshimau",
    expected: "DBC定義のバイト順でCAN信号を復号すること",
    expectedAnswer: "dbc teiginobaitojunde can shingouwofukugousurukoto",
    actual: "受信値0x0BB8に対し、期待値30.00Vではなく471.15Vと表示される",
    actualAnswer: "jushinchi0x0bb8nitaishi kitaichi30.00vdewanaku471.15vtohyoujisareru",
    reproducibility: "3/3",
  },
  {
    scenarioId: "automotive-bus-off-recovery-receive-stopped",
    projectId: "automotive",
    difficulty: "advanced",
    subject: "ADAS ECUでBus-Off復帰後もCAN受信が再開されない",
    subjectAnswer: "adas ecu debus-offfukkigomocan jushingasaikaisarenai",
    detail: "CANバス負荷率90%以上の状態でBus-Offを発生させて復帰処理を実行しても、解除から30秒経過後もADAS ECUのCAN受信が再開されない",
    detailAnswer: "can basuhukaritu90%ijounojoutaidebus-offwohasseisasetefukkishoriwojikkoushitemo kaijokara30byoukeikagomoadas ecu no can jushingasaikaisarenai",
    expected: "Bus-Off解除後500ms以内にADAS ECUのCAN受信を再開すること",
    expectedAnswer: "bus-offkaijogo500msinaini adas ecu no can jushinwosaikaisurukoto",
    actual: "Bus-Off解除から30秒経過後もADAS ECUのCAN受信が再開されない",
    actualAnswer: "bus-offkaijokara30byoukeikagomoadas ecu no can jushingasaikaisarenai",
    reproducibility: "1/50",
  },
  {
    scenarioId: "payment-idempotency-key-double-charge",
    projectId: "payment",
    difficulty: "intermediate",
    subject: "決済APIで同じ冪等キーを再利用すると売上が二重確定されてしまう",
    subjectAnswer: "kessaiapideonajibekitouki-wosairiyousurutouriageganijuukakuteisareteshimau",
    detail: "5,000円の決済に使用した冪等キーで10秒後に同額の決済を再試行すると、異なる取引IDで売上が2件確定してしまう",
    detailAnswer: "5,000ennnokessainishiyoushitabekitouki-de10byougonidougakunokessaiwosaishikousuruto kotonarutorihikiiddeuriagega2kennkakuteishiteshimau",
    expected: "同じ冪等キーには最初の処理結果を返すこと",
    expectedAnswer: "onajibekitouki-nihahajimenoshorikekkawokaesukoto",
    actual: "同じ冪等キーに対し、異なる取引IDで売上が2件確定する",
    actualAnswer: "onajibekitouki-nitaishi kotonarutorihikiiddeuriagega2kennkakuteisuru",
    reproducibility: "2/10",
  },
  {
    scenarioId: "payment-timeout-authorization-remains",
    projectId: "payment",
    difficulty: "advanced",
    subject: "決済APIのタイムアウト後もカードの与信枠が残ってしまう",
    subjectAnswer: "kessaiapinotaimuautogomoka-donoyoshinnwakuganokotteshimau",
    detail: "30秒でタイムアウトした取引を再照会すると決済失敗となっているが、50,000円の与信枠が15分後も残ってしまう",
    detailAnswer: "30byoudetaimuautoshitatorihikiwosaishoukaisurutokessaishippaitonatteiruga 50,000ennnoyoshinnwakuga15pungomonokotteshimau",
    expected: "再照会で決済失敗を確定した場合、5分以内に与信を取り消すこと",
    expectedAnswer: "saishoukaidekessaishippaiwokakuteishitabaai 5puninainiyoshinwotorikesukoto",
    actual: "決済失敗の確定から15分後も50,000円の与信枠が残っている",
    actualAnswer: "kessaishippainokakuteikara15pungomo50,000ennnoyoshinnwakuganokotteiru",
    reproducibility: "1/40",
  },
  {
    scenarioId: "medical-weight-conversion-dose-thousandfold",
    projectId: "medical",
    difficulty: "intermediate",
    subject: "投薬量計算で体重の単位変換が行われず投薬量が1000倍になってしまう",
    subjectAnswer: "touyakuryoukeisanndetaijuunotannihennkanngaokonawarezutouyakuryouga1000baininatteshimau",
    detail: "体重18,000gの患者に10mg/kgの薬剤を指定して自動計算すると、期待値180mgに対して180,000mgと算出されてしまう",
    detailAnswer: "taijuu18,000gnokannjani10mg/kgnoyakuzaiwoshiteishitejidoukeisansuruto kitaichi180mgnitaishite180,000mgtosannshutsusareteshimau",
    expected: "体重18,000gを18kgへ変換し、投薬量を180mgと計算すること",
    expectedAnswer: "taijuu18000gwo18kghehenkanshi touyakuryouwo180mgtokeisansurukoto",
    actual: "投薬量が期待値180mgではなく180,000mgと算出される",
    actualAnswer: "touyakuryougakitaichi180mgdewanaku180,000mgtosannshutsusareru",
    reproducibility: "3/3",
  },
  {
    scenarioId: "medical-lab-result-resend-duplicate",
    projectId: "medical",
    difficulty: "advanced",
    subject: "検査結果連携で同じ検査結果を再送すると患者記録が重複登録されてしまう",
    subjectAnswer: "kensakekkarenkeideonajikensakekkawosaisousurutokannjakirokugajouhukutourokusareteshimau",
    detail: "検査結果ID「LAB-9031」の連携データを再送すると、同じ測定時刻と測定値の結果が患者記録に2件登録されてしまう",
    detailAnswer: "kensakekkaid lab-9031norenkeide-tawosaisousuruto onajisokuteijikokutosokuteichinokekkagakannjakirokuni2kenntourokusareteshimau",
    expected: "検査結果IDを使って重複登録を防止すること",
    expectedAnswer: "kensakekka id wotukattetyouhukutourokuwoboushisurukoto",
    actual: "同じ測定時刻と測定値の検査結果が患者記録に2件登録される",
    actualAnswer: "onajisokuteijikokutosokuteichinokensakekkagakannjakirokuni2kenntourokusareru",
    reproducibility: "1/30",
  },
];
